version: "2.0"
services:

    gps-svc:
        build: gps-svc
        ports:
            - 6061:6061        
        depends_on:
            - my_sql
        environment:
            MYSQL_ENDPOINT: mysql
            MYSQL_USER: dev
            MYSQL_PASSWORD: changeme
            MYSQL_DATABASE: djapp
            PYTHONUNBUFFERED: 0  # agrego esto para ver los prints de python en la terminal                    

    svc-temas:
        build: svc-temas
        ports:
            - 8081:8081
        depends_on:
            - mysql
        environment:
            MYSQL_ENDPOINT: mysql
            MYSQL_USER: dev
            MYSQL_PASSWORD: changeme
            MYSQL_DATABASE: djapp
            PYTHONUNBUFFERED: 0  # agrego esto para ver los prints de python en la terminal

    svc-likes:
        build: svc-likes
        ports:
            - 8088:8088
        depends_on:
            - mysql
        environment:
            MYSQL_ENDPOINT: mysql
            MYSQL_USER: dev
            MYSQL_PASSWORD: changeme
            MYSQL_DATABASE: djapp
            PYTHONUNBUFFERED: 0  # agrego esto para ver los prints de python en la terminal
       
    mysql:
        image: mysql:5.7
        ports:
            - 3307:3306
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_USER: dev
            MYSQL_PASSWORD: changeme
            MYSQL_DATABASE: djapp