version: "2.0"
services:
       
    djapp:
        build: .
        ports:
            - 9090:9090
        environment:
            MYSQL_ENDPOINT: ${MYSQL_ENDPOINT}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        ports:
            - 3307:3306
        volumes:
            - ./database:/var/lib/mysql

        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        